### ISSUE TITLE
起動時にログイン画面が表示される

### ISSUE THREAD

**Issue by Hayao0819** [nexryai/project-alexandrite#12]
ライブ環境GDMの自動ログインを設定してユーザー選択を行わくても良いようにしてください。

**Comment by nexryai** [comment]
了解しました。`/etc/gdm/custom.conf`で自動ログインを行うよう設定してみます。

**Comment by nexryai** [comment]
このコミットで修正しました。
https://github.com/nexryai/project-alexandrite/commit/f6fafea349901bf3920ebf56e947449290ace591
