### ISSUE TITLE
Dash to panelで右クリックが効かない

### ISSUE THREAD

**Issue by nexryai** [nexryai/project-alexandrite#17]
これはDash to panel側の不具合でgnome41環境で発生するようです。
残念ながら私には修正してPRを送る技術力もないので修正されるのを待つしか無いです。ただしもし修正のPRが他の方から出ていたら本家より先にマージしてアップデートとして配布します。
https://github.com/home-sweet-gnome/dash-to-panel/issues/1488

**Comment by philippun1** [comment]
バグが修正されました。[#1506](https://github.com/home-sweet-gnome/dash-to-panel/pull/1506)

**Comment by nexryai** [comment]
Thank you so much!
